- id: prettier-conda
  name: prettier-conda
  description: 'An opinionated code formatter'
  entry: prettier
  language: conda
  types: [text]
  args: ["--write", "--list-different", "--ignore-unknown"]
